--- # Installing Httpd Package
- name: Install epel-release
  yum: pkg=epel-release state=latest

- name: Install LEMP Packages
  yum: pkg={{ item }} state=latest
  with_items:
          - nginx
          - yum-utils
          - mariadb
          - mariadb-server

- name: mysqlstart
  service: name=mariadb state=started
<<<<<<< HEAD
          
  #- name: mysql_secure_installation
  #  raw: echo -e "\ny\ny\nmysqlpass123!!\nmysqlpass123!!\ny\ny\ny\ny" | /usr/bin/mysql_secure_installation
=======
>>>>>>> 6d07adf34f8b18553a301127f18502205d16a564

- name: Install Remi RPM
  yum: pkg=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present

- name: Enable Remi Repo
  raw: yum-config-manager --enable remi-php71

- name: Install PHP Packages
  yum: pkg={{ item }} state=latest
  with_items:
          - php-fpm
          - php-common
          - php-opcache
          - php-pecl-apcu
          - php-cli
          - php-pear
          - php-pdo
          - php-mysqlnd
          - php-pgsql
          - php-pecl-mongodb
          - php-pecl-redis
          - php-pecl-memcache
          - php-pecl-memcached
          - php-gd
          - php-mbstring
          - php-mcrypt
          - php-xml
