--- # Start Apache Service
- name: Starting LEMP Services
  service: name={{ item }} state=started enabled=yes
  with_items:
          - nginx
          - mariadb

- name: Starting PHP-FPM
  service: name=php-fpm state=started enabled=yes
