--- # Installing Httpd Package
- name: install zabbix repo
  yum: pkg=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm state=present

- name: install zabbix packages
  yum: pkg=zabbix-agent state=latest

- name: copy template conf
  template: src=zabbix_agentd.conf.js2 dest=/etc/zabbix/zabbix_agentd.conf
  with_items:
          - { ip: "{{ ipaddress }}", host: "{{ hostname }}" }
