--- #Install/Confgire dovecot
- name: Install Dovecot
  yum: pkg={{ item }} state=latest
  with_items:
          - dovecot
          - dovecot-mysql


- name: Copy Dovecot conf files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
          - { src: 'dovecot/10-mail.conf',   dest:'/etc/dovecot/conf.d/10-mail.conf'   } 
          - { src: 'dovecot/10-auth.conf',   dest: '/etc/dovecot/conf.d/10-auth.conf'  }
          - { src: 'dovecot/10-ssl.conf',    dest: '/etc/dovecot/conf.d/10-ssl.conf'   }
          - { src: 'dovecot/15-lda.conf',    dest: '/etc/dovecot/conf.d/15-lda.conf'   }
          - { src: 'dovecot/10-master.conf', dest: '/etc/dovecot/conf.d/10-master.conf'}

- name: Copy /etc/dovecot/dovecot-sql.conf.ext
  template: src=dovecot-sql.conf.js2 dest=/etc/dovecot/dovecot-sql.conf.ext
  with_items: "{{ passw }}"
