--- # Installation for mail server

#- name: Install Packages
#  yum: pkg={{ item }} state=latest
#  with_items:
#          - wget
#          - mariadb
#          - mariadb-server
#          - postfix
#          - php
#          - php-mysql
#          - php-imap
#          - php-mbstring
#          - php-common

- name: Start Mariadb
  service: name=mariadb state=started enabled=yes

- name: Initialise mariadb
  script: files/mysql.sh
  ignore_errors: yes

- name: Adding root mysql without pass
  template: src=my.cnf.js2 dest=/root/.my.cnf force=no
  with_items: "{{ passw }}"

- name: Mysql add postfix               
  script: postfix.sh  
            
- name: Create mail user
  user: name=vmail state=present groups=mail shell=/sbin/nologin uid=150 home=/var/vmail comment="Virtual Mail User"

- name: Create vmail directory
  file: path=/var/vmail state=directory owner=vmail group=mail mode=0770

- name: Install Postfix
  unarchive: src=http://downloads.sourceforge.net/project/postfixadmin/postfixadmin/postfixadmin-3.0.2/postfixadmin-3.0.2.tar.gz dest=/var/www/html/ remote_src=True

- name: Copy postfix config.inc.php
  template: src=config.inc.js2 dest=/var/www/html/postfixadmin-3.0.2/config.inc.php
  with_items: "{{ passw }}"

- name: Set folder permissions
  file: path=/var/www/html/postfixadmin-3.0.2/ owner=nginx group=nginx recurse=yes

- name: Initialise postfixadmin required
  pause: prompt='Please visit http://{{ inventory_hostname }}/postfixadmin-3.0.2/setup.php, once completed, Press Enter to continue OR Ctrl+c and then "a" to abort'

- name: Create Postfix Admin User
  raw: bash /var/www/html/postfixadmin-3.0.2/scripts/postfixadmin-cli admin add admin@your_domain_idroot.net --password mysqlpass123!! --password2 mysqlpass123!! --superadmin 1 --active 1
