--- #Install/Configure SpamAssassin
- name: Install SpamAssassin
  yum: pkg=spamassassin state=latest

- name: Create spamd group
  group: name=spamd state=present

- name: Create spamd user
  user: name=spamd state=present shell=/bin/false home=/var/log/spamassassin

- name: Permissions for spamd
  file: path=/var/log/spamassassin state=directory owner=spamd group=spamd
